use_frameworks!

platform :ios, '9.0'

workspace 'MGSegmentedProgressBar'

target 'MGSegmentedProgressBar_Example' do
    pod 'MGSegmentedProgressBar', :path => '../'
end

target 'MGSegmentedProgressBar_Tests' do
    pod 'MGSegmentedProgressBar', :path => '../'
    pod 'Quick'
    pod 'Nimble'
    
    inherit! :search_paths
end
